# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Armaria < Formula
  desc "Armaria is a fast, open, and local first bookmarks manager."
  homepage "https://github.com/JonathanHope/armaria"
  version "0.0.25"
  license "MIT"
  depends_on :macos

  on_macos do
    url "https://github.com/JonathanHope/armaria/releases/download/v0.0.25/armaria_0.0.25_darwin_all.zip", using: CurlDownloadStrategy
    sha256 "51802c6b5a47cea0c7255c4505ed9fe92b1ce3dd62a73bdbca52729a3bce2308"

    def install
      bin.install "armaria"
      bin.install "armaria-host"
    end
  end
end
