# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Armaria < Formula
  desc "Armaria is a fast, open, and local first bookmarks manager."
  homepage "https://github.com/JonathanHope/armaria"
  version "0.0.19"
  license "MIT"
  depends_on :macos

  on_macos do
    url "https://github.com/JonathanHope/armaria/releases/download/v0.0.19/armaria_0.0.19_darwin_all.zip", using: CurlDownloadStrategy
    sha256 "35017469c8b18a69bc42928dcfc70980b9a8a20af6f773067944cde7e454c439"

    def install
      bin.install "armaria"
      bin.install "armaria-host"
    end
  end
end
